// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdzfymqgsylrmfnbvdoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkemZ5bXFnc3lscm1mbmJ2ZG9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDczMjEsImV4cCI6MjA2ODY4MzMyMX0.DrYXH9qiz_9aZUHmtA0ttIJHij7uV7KV7U4Fk23GhJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});